version: "3.5"

services:
  hadoop:
    build: .
    container_name: hdoop
    ports:
      - 9870:9870
      - 9864:9864
      - 8088:8088
    volumes:
       - /home/bhaskar/Desktop/Distributed-Systems/Assignment2/:/mnt
  
volumes:
  x: